### ISSUE TITLE
update roadmap in index.html

### ISSUE THREAD

**Issue by jimscarver** [rchain/www.rchain.coop#58]
- [ ] Blockmerge needs to be in the future
 - [ ] the forks are missing
 - [ ] needs hackathon date, if any.
